"""Codepilot 工具子系统的公开 API。"""

# 本文件是 tools 包的统一导出入口。
# 所有外部模块（runtime、core、extensions 等）都通过此文件导入工具子系统类型，
# 而不直接引用内部模块，以保持清晰的依赖边界。

from .builtins import create_builtin_registrations
from .codecs import (
    DataclassCodec,
    JsonObjectCodec,
    ToolCodecError,
    ToolSchemaError,
    UnverifiedJsonCodec,
    validate_json_schema,
)
from .contracts import (
    CancellationToken,
    CleanupStack,
    EffectReporter,
    ProgressReporter,
    ToolAccessResolver,
    ToolCategory,
    ToolCodec,
    ToolCheckpointPort,
    ToolControlPort,
    ToolExecutionContext,
    ToolExecutionPort,
    ToolExecutionRequest,
    ToolHandler,
    ToolHandlerError,
    ToolOutputRenderer,
    ToolRegistration,
    ToolResumePreparation,
    ToolSource,
    ToolSpec,
)
from .execution import (
    ExecutionController,
    ToolExecutionCancelledError,
    ToolExecutionControlError,
    ToolExecutionTimeoutError,
    ToolProgressEvent,
    ToolQueueFullError,
    ToolQueueTimeoutError,
    ToolRuntimeLimits,
)
from .registry import (
    StaleToolRegistrationError,
    ToolCatalogEntry,
    ToolCatalogSnapshot,
    ToolRegistrationConflictError,
    ToolRegistrationNotFoundError,
    ToolRegistry,
    ToolRegistryError,
)
from .results import (
    ArtifactContent,
    ArtifactRef,
    ImageContent,
    TextContent,
    ToolError,
    ToolResult,
    ToolTiming,
    to_tool_result_message,
)
from .runtime import ToolRuntime
from .security import (
    ApprovalChallenge,
    ApprovalGrant,
    ApprovalResponse,
    ConcurrencyPolicy,
    OutputLimits,
    OutputTrustPolicy,
    PermissionDecision,
    PermissionEngine,
    PermissionRule,
    TimeoutPolicy,
    ToolAccessRequest,
    ToolAccessResolution,
    ToolEffect,
    ToolEffectKind,
    ToolMode,
    ToolPolicy,
    ToolResource,
)
from .state import (
    InMemoryToolStateStore,
    InteractionRequest,
    InteractionResponse,
    ToolAttemptRecord,
    ToolAttemptState,
    ToolStateConflictError,
    ToolStateStore,
)
from .state_store import CheckpointToolStateStore, FileToolGrantStore

__all__ = [
    "ApprovalChallenge",
    "ApprovalGrant",
    "ApprovalResponse",
    "ArtifactContent",
    "ArtifactRef",
    "CancellationToken",
    "CleanupStack",
    "CheckpointToolStateStore",
    "ConcurrencyPolicy",
    "DataclassCodec",
    "EffectReporter",
    "ExecutionController",
    "FileToolGrantStore",
    "ImageContent",
    "InMemoryToolStateStore",
    "InteractionRequest",
    "InteractionResponse",
    "JsonObjectCodec",
    "OutputLimits",
    "OutputTrustPolicy",
    "PermissionDecision",
    "PermissionEngine",
    "PermissionRule",
    "ProgressReporter",
    "StaleToolRegistrationError",
    "TextContent",
    "TimeoutPolicy",
    "ToolAccessRequest",
    "ToolAccessResolution",
    "ToolAccessResolver",
    "ToolAttemptRecord",
    "ToolAttemptState",
    "ToolCatalogEntry",
    "ToolCatalogSnapshot",
    "ToolCategory",
    "ToolCodec",
    "ToolCodecError",
    "ToolCheckpointPort",
    "ToolControlPort",
    "ToolEffect",
    "ToolEffectKind",
    "ToolError",
    "ToolExecutionCancelledError",
    "ToolExecutionContext",
    "ToolExecutionPort",
    "ToolExecutionControlError",
    "ToolExecutionRequest",
    "ToolExecutionTimeoutError",
    "ToolHandler",
    "ToolHandlerError",
    "ToolMode",
    "ToolOutputRenderer",
    "ToolPolicy",
    "ToolProgressEvent",
    "ToolQueueFullError",
    "ToolQueueTimeoutError",
    "ToolRegistration",
    "ToolResumePreparation",
    "ToolRegistrationConflictError",
    "ToolRegistrationNotFoundError",
    "ToolRegistry",
    "ToolRegistryError",
    "ToolResource",
    "ToolResult",
    "ToolRuntime",
    "ToolRuntimeLimits",
    "ToolSchemaError",
    "ToolSource",
    "ToolSpec",
    "ToolStateConflictError",
    "ToolStateStore",
    "ToolTiming",
    "UnverifiedJsonCodec",
    "create_builtin_registrations",
    "to_tool_result_message",
    "validate_json_schema",
]
