from __future__ import annotations

"""Core agent loop public surface."""

from .contracts import (
    AgentContext,
    AgentLoopInput,
    AgentLoopLimits,
    AgentLoopOutcome,
    AgentLoopPorts,
    AgentLoopStatus,
    AgentMessage,
    AgentResumeInput,
    ContextPort,
    ContextPreparationRequest,
    CoreRunBoundary,
    CoreWaitingRequest,
    EventSink,
    PreparedAgentContext,
    PreparedContext,
    PrepareContextFn,
    RetryPolicy,
    RunCorrelation,
    RunStatePort,
    ToolExecutionMode,
    WorkspaceEffects,
)
from .model_step import convert_to_llm
from .plan import (
    PlanItem,
    PlanSnapshot,
    PlanSnapshotItem,
    PlanState,
    PlanValidationError,
    PlanningBudgetProfile,
    RunMode,
    ensure_planning_budget_profile,
    ensure_run_mode,
)
from .run_guard import RunGuard, RunGuardDecision
from .runner import AgentEventEmitter, maybe_await, resume_agent_loop, run_agent_loop
from .state import RunState, new_run_id

__all__ = [
    "AgentContext",
    "AgentLoopInput",
    "AgentLoopLimits",
    "AgentLoopOutcome",
    "AgentLoopPorts",
    "AgentLoopStatus",
    "AgentMessage",
    "AgentResumeInput",
    "ContextPort",
    "ContextPreparationRequest",
    "CoreRunBoundary",
    "CoreWaitingRequest",
    "EventSink",
    "PreparedAgentContext",
    "PreparedContext",
    "PrepareContextFn",
    "RetryPolicy",
    "RunCorrelation",
    "RunStatePort",
    "ToolExecutionMode",
    "WorkspaceEffects",
    "convert_to_llm",
    "PlanItem",
    "PlanSnapshot",
    "PlanSnapshotItem",
    "PlanState",
    "PlanValidationError",
    "PlanningBudgetProfile",
    "RunMode",
    "ensure_planning_budget_profile",
    "ensure_run_mode",
    "RunGuard",
    "RunGuardDecision",
    "AgentEventEmitter",
    "maybe_await",
    "run_agent_loop",
    "resume_agent_loop",
    "RunState",
    "new_run_id",
]
