"""会话层状态和恢复契约 —— 会话状态、运行状态、检查点、消息记录的规范定义。

sessions 层拥有四个核心事实：
- 会话状态（SessionState）：会话的元信息
- 运行状态（RunState）：单次运行的完整生命周期
- 规范消息（MessageRecord）：会话中的消息记录
- 非权威审计事件（events）：异步事件日志
"""

from .contracts import (
    CHECKPOINT_SCHEMA_VERSION,
    MESSAGE_RECORD_SCHEMA_VERSION,
    RUN_STATE_SCHEMA_VERSION,
    SESSION_STATE_SCHEMA_VERSION,
    CancelRunIntent,
    ComponentCheckpoint,
    MessageCursor,
    MessageRecord,
    ModelRef,
    PreparedAgentRun,
    RecoveryBundle,
    RecoveryIssue,
    RecoveryRequest,
    RecoveryResult,
    RollbackBaselineRef,
    RunCheckpoint,
    RunCommitKind,
    RunState,
    SessionCommandIntent,
    SessionCommandRecord,
    SessionIntent,
    SessionResumeIntent,
    SessionRunIntent,
    SessionRunRecord,
    SessionOptions,
    SessionState,
    SessionStateConflictError,
    SessionStateValidationError,
    SessionView,
    WaitingState,
    WorkspaceCheckpoint,
    WorkspaceEffectsSnapshot,
    WorkspaceRecoveryState,
    validate_run_state,
    validate_run_transition,
)
from .repository import FileSessionRepository
from .service import (
    BeginRunRequest,
    BeginRunResult,
    CommitRunBoundaryReceipt,
    CommitRunBoundaryRequest,
    CreateSessionRequest,
    ResumeRunRequest,
    SessionStateService,
    new_session_id,
)
__all__ = [
    "CHECKPOINT_SCHEMA_VERSION",
    "MESSAGE_RECORD_SCHEMA_VERSION",
    "RUN_STATE_SCHEMA_VERSION",
    "SESSION_STATE_SCHEMA_VERSION",
    "SessionState",
    "RunState",
    "RunCheckpoint",
    "RunCommitKind",
    "MessageRecord",
    "MessageCursor",
    "ModelRef",
    "WaitingState",
    "ComponentCheckpoint",
    "WorkspaceCheckpoint",
    "WorkspaceEffectsSnapshot",
    "WorkspaceRecoveryState",
    "RecoveryRequest",
    "RecoveryResult",
    "RecoveryBundle",
    "RecoveryIssue",
    "SessionStateValidationError",
    "SessionStateConflictError",
    "validate_run_state",
    "validate_run_transition",
    "FileSessionRepository",
    "SessionStateService",
    "CreateSessionRequest",
    "BeginRunRequest",
    "BeginRunResult",
    "CommitRunBoundaryReceipt",
    "CommitRunBoundaryRequest",
    "ResumeRunRequest",
    "SessionRunIntent",
    "SessionResumeIntent",
    "SessionCommandIntent",
    "CancelRunIntent",
    "SessionIntent",
    "PreparedAgentRun",
    "RollbackBaselineRef",
    "SessionRunRecord",
    "SessionCommandRecord",
    "SessionView",
    "SessionOptions",
    "new_session_id",
]
